---    
        
- name: Get list of groups
  command: cut -d ":" -f 1 /etc/group
  register: cuckoo_register_groups
  
- name: Add cuckoo user to libvirtd group
  become: True
  user: name='cuckoo'
        groups={{ cuckoo_register_groups.stdout.split('\n') | intersect(cuckoo_libvirt_group) | join(',') }}
        append=yes

- name: Set network interface used by tcpdump
  become: True
  ini_file:
    dest: '{{ cuckoo_cwd }}/conf/kvm.conf'
    section: 'kvm'
    option: 'interface'
    value: '{{ cuckoo_interface }}'
  notify: restart cuckoo
    