---

# Set up the management node for distributed cuckoo
- block:

    # Not working :( What is wrong with delegate_facts?
    # - name: Tell every worker node who is the management node
    #   set_fact:
    #     cuckoo_management_host: "{{ inventory_hostname }}"
    #   delegate_to: "{{ item }}"
    #   delegate_facts: True
    #   with_items: "{{ ansible_play_batch }}"    
    #   when: cuckoo_management_host is not defined
    #   run_once: True

    - name: Install cuckoo distributed dependencies
      pip:
        name: cuckoo[distributed]

    # Install mysql and add a database
    - include_role:
        name: geerlingguy.mysql
      vars:
        mysql_enabled_on_startup: yes
        mysql_databases:
          - name: distributed
    
    - name: Inform distributed to use mysql
      replace:
        path: '{{ cuckoo_cwd }}/distributed/settings.py'
        regexp: '^(SQLALCHEMY_DATABASE_URI).+$'
        replace: '\1 = "mysql://root:root@localhost/distributed"'

    # Set up nginx and uwsgi configuration for distributed cuckoo
    - include: configure_nginx_uwsgi.yml command="distributed server -H 0" file="distributed"

    - name: Install Cuckoo Distributed systemd service
      template: src=cuckoo-distributed.service.j2 dest=/etc/systemd/system/cuckoo-distributed.service owner=root group=root mode=0644
      notify: start cuckoo-distributed
      become: True
      
    - name: Restarts services if needed
      meta: flush_handlers

    - name: Test if distributed is running correctly
      uri: url="http://localhost:9003/api/node"
      failed_when: false
      register: cuckoo_distributed_test

    - block:
        - service: name=nginx state=restarted
        - service: name=uwsgi state=restarted
      when: cuckoo_distributed_test.status == 500
      
  when: cuckoo_management_node
  
- block:

  # Install mysql database on every node
  # By default, cuckoo uses sqlite which is not suited for cuckoo distributed
  - include_role:
      name: geerlingguy.mysql
    vars:
      mysql_enabled_on_startup: yes
      mysql_databases:
        - name: cuckoo
    become: yes
    become_method: sudo
  
  - name: Inform cuckoo to use mysql
    become: True
    ini_file:
      dest: '{{ cuckoo_cwd }}/conf/cuckoo.conf'
      section: 'database'
      option: 'connection'
      value: 'mysql://root:root@localhost/cuckoo'
    notify: restart cuckoo

  - meta: flush_handlers    
    
  - name: Wait for distributed cuckoo to start
    wait_for:
      port: 9003
      connect_timeout: 10
    delegate_to: "{{ cuckoo_management_host }}"
    delegate_facts: True
    
  - name: Add nodes to cuckoo distributed 
    uri:
      url: "http://localhost:9003/api/node"
      method: POST
      body: "name={{ inventory_hostname }}&url=http://{{ ansible_default_ipv4.address }}:8090/"
      return_content: True
    register: result
    failed_when: not result.json.success and result.json.message != "There is already a node with this name"
    delegate_to: "{{ cuckoo_management_host }}"
    
  when: cuckoo_worker_node