---

- name: Install requirements
  package:
    name: "{{ cuckoo_apt_requirements }}"
    state: latest

- name: Install requirements for distributed
  package:
    name: "{{ cuckoo_distributed_apt_requirements }}"
    state: latest
  when: cuckoo_management_node
    
- name: Update pip
  command: pip install --upgrade pip
    
- name: Create cuckoo group
  group: name=cuckoo

- name: Create cuckoo user
  user: name=cuckoo groups=cuckoo

- name: Install cuckoo from pip
  pip:
    name: setuptools cuckoo

- name: Install setfacl support
  package: name=acl

- name: Setcap tcptump permissions
  command: setcap cap_net_raw,cap_net_admin=eip /usr/sbin/tcpdump

- name: Disable AppArmor for tcpdump
  command: aa-disable /usr/sbin/tcpdump
  failed_when: false

- name: Give proper permissions
  file: path={{ cuckoo_cwd }} state=directory recurse=yes owner=cuckoo group=cuckoo

- name: Check if the CWD already exists
  stat: path={{ cuckoo_cwd }}/conf
  register: cuckoo_stat_result
  
- name: Create cuckoo CWD
  command: /usr/local/bin/cuckoo
  when: cuckoo_stat_result.stat.exists == False
  become: yes
  become_user: cuckoo
