Vagrant.require_version ">= 1.7.0"

Vagrant.configure("2") do |config|

  # Do not replace vagrant default ssh key
  config.ssh.insert_key = false

  config.vm.define :testvm do |testvm|
    testvm.vm.box = "elastic/ubuntu-16.04-x86_64"
    # If you wish to change that ip, change it in inventory files too
    testvm.vm.network :private_network, :ip => '192.168.101.2'
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.storage_pool_name = "default"
    libvirt.memory = "1024"
  end
end
