---

- name: restart cuckoo
  become: yes
  become_method: sudo
  service: name=cuckoo state=restarted enabled=yes

- name: start cuckoo-rooter
  become: yes
  become_method: sudo
  service: name=cuckoo-rooter state=started enabled=yes  

- name: start cuckoo-distributed
  become: yes
  become_method: sudo
  service: name=cuckoo-distributed state=started enabled=yes
  
- name: restart uwsgi
  become: yes
  become_method: sudo
  service: name=uwsgi state=restarted enabled=yes
  
- name: restart nginx
  become: yes
  become_method: sudo
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  become: yes
  become_method: sudo
  service: name=nginx state=reloaded
    
